:navtitle: Glossary


= Glossary

// == List of Keywords for Mobile SDK and Plugins

== a

Anyline Mobile SDK for [Android/iOS/UWP/.NET]::
Library that allows you to use the provided functionality in a platform-native manner

Anyline Plugin for [Cordova/Flutter/ReactNative]::
Plugin for the respective platform that allows a simple way to integrate the Anyline Mobile SDK for the respective cross-platform technology


== j

JSON (JavaScript Object Notation)::
An open standard file format and data interchange format that uses human-readable text to store and transmit data objects consisting of attribute–value pairs and arrays (or other serializable values)

JSON Schema::
Specifies a JSON-based format to define the structure of JSON data for validation, documentation, and interaction control.


== s

ScanViewConfig::
JSON File or Text (String) that defines how the SDK should behave.

== t

Technical Capability / Scanning Capability / ScanPlugin::
Each Technical Capability of the Mobile SDK is fine-tuned to deliver the best results for the kind of data you are looking to digitize. The Mobile SDK includes for each Technical Capability a respective ScanPlugin component. Examples for Technical Capabilities include: Barcode, Meter, License Plate, Tire Size, Vehicle Identification Number, etc...


== p

PluginConfig::
The PluginConfig configures the Mobile SDK to use the corresponding Technical Capability, defining what type of data the Mobile SDK is expected to digitize. Each ScanViewConfig requires at least one PluginConfig to be present. Each type of PluginConfig (e.g. _tireSizeConfig_, _barcodeConfig_, etc.) has a corresponding PluginResult (e.g. _tireSizeResult_, _barcodeResult_, etc.). In that sense, PluginConfig and PluginResult can be regarded similarly to _request to_ and _response from_ the Mobile SDK.


PluginResult::
The Mobile SDK returns digitized data as a type of PluginResult (e.g. _tireSizeResult_, _barcodeResult_, etc.), corresponding to the relevant PluginConfig (e.g. _tireSizeConfig_, _barcodeConfig_, etc.) the Mobile SDK is configured with.


PluginConfig & PluginResult::
The PluginConfig configures the Mobile SDK to use the corresponding Technical Capability, defining what type of data the Mobile SDK is expected to digitize. Each ScanViewConfig requires at least one PluginConfig to be present. Each type of PluginConfig (e.g. _tireSizeConfig_, _barcodeConfig_, etc.) has a corresponding PluginResult (e.g. _tireSizeResult_, _barcodeResult_, etc.). In that sense, PluginConfig and PluginResult can be regarded similarly to _request to_ and _response from_ the Mobile SDK.


include::main-component::partial$tip-get-help.adoc[]
