//
//  AppDemoLicense.h
//  AnylineExamples
//
//  Created by Philipp Müller on 07/12/16.
//  Copyright © 2017 Anyline GmbH. All rights reserved.
//

#ifndef Anyline_ALAppDemoLicenses_h
#define Anyline_ALAppDemoLicenses_h


#define kDemoAppLicenseKey \
@"eyAiZGVidWdSZXBvcnRpbmciOiAib24iLCAiaW9zSWRlbnRpZmllciI6IFsgImlvLmFueWxpbmUuZXhhbXBsZXMuYnVuZGxlIiwgImlvLmFueWxpbmUuQW55bGluZUV4YW1wbGVzIiBdLCAibGljZW5zZUtleVZlcnNpb24iOiAyLCAibWFqb3JWZXJzaW9uIjogIjMiLCAicGluZ1JlcG9ydGluZyI6IHRydWUsICJwbGF0Zm9ybSI6IFsgImlPUyIgXSwgInNjb3BlIjogWyAiQUxMIiBdLCAic2hvd1BvcFVwQWZ0ZXJFeHBpcnkiOiBmYWxzZSwgInNob3dXYXRlcm1hcmsiOiB0cnVlLCAidG9sZXJhbmNlRGF5cyI6IDkwLCAidmFsaWQiOiAiMjAyMC0xMi0zMSIgfQpKZTR0cjJlMXNOWVNuUkZvL2FJVVNEZGM1WTQ1eUhVSWZLOUlFM0ZxcW8wRFJzQ0pqUU52bVNEeTg3WUVzalpuCnJNMjRFQkJ2Ly9aL0VISmowUUk4aCtWTURRTi9vbE9mRXJ1Z1A1OE0vbmptdXZWMTJ3cTNkNkk3bThHNWxZOXkKa05iOHJDVmpaRFBTRW83amkxRTlwZENoOUpDM3hLYUEvMVIyMVUxcWlKZldBZTJBWThLNFhPb1huNXprZkl6MApXSDZsaGd2NktudUlyMFIyRHkrNGh4aGQ3WHRNTUo1TDE2RUpZM29CamV2ekM4b1dkZE40OWsvZlVUWmdtb1ZCCkI5b2pLK3NBUlFUMmNBRE0rWTFpZnhKOGdMMHJVUHlpa1FPTThqRzdDdGNrVys4ZFRiZEFxVmQ0M1I0Y1VQSUoKSVpNdWI3Mm4wQTFYZy9hWWREbkQxQT09Cg=="

#endif
